sitename = "mircoveltri.me"
title = "mircoveltri.me"
description = "My Welcome Page"
WelcomeMessage = "Hello, I'm Mirco"
logo = "images/favicon/favicon.ico"

gdpr = false

[Webmaster]
  author = "indaco"
  license = "MIT"

[Contact]
  email = "hi@mircoveltri.me"

[Address]
  addressRegion = "Milan"
  postalCode = "20100"
  addressCountry = "Italy"