name: Production Deploy
on:
  push:
    branches: [stable]
jobs:
  web-deploy:
    runs-on: ubuntu-latest
    env: VITE_PUBLIC_BASE_PATH: http://mircoveltri.me
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: npm install

      - run: npm run build

      - name: FTP Deploy to production domain
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.production_ftp_hostname }}
          username: ${{ secrets.production_ftp_username }}
          password: ${{ secrets.production_ftp_password }}
          dry-run: false
          local-dir: ./build/
          server-dir: ${{ secrets.production_server_folder }}
          exclude: .git*
            - .git*/**
            -  **/.git*/**
            - node_modules/**
            - node_modules/**/*
